from marshmallow import Schema, fields


class ClientSchema(Schema):
    type_id = fields.Int(required=True)
    identification = fields.Int(required=True)
    name = fields.Str(required=True)
    phone = fields.Str()
    email = fields.Str()
    macro_portfolio = fields.Str()
    payment_probability = fields.Float()
    customer_segment = fields.Str()
    customer_type = fields.Str()
    customer_actions = fields.Str()
    days_in_arrears = fields.Int()
    capital_balance = fields.Float()
    income_range = fields.Str()
    income_trend = fields.Str()
    sector_indebtedness = fields.Float()
    sector_installments_sum = fields.Float()
    bank_installments_sum = fields.Float()
    entity_1_debt_name = fields.Str()
    entity_1_debt_value = fields.Float()
    entity_2_debt_name = fields.Str()
    entity_2_debt_value = fields.Float()
    entity_3_debt_name = fields.Str()
    entity_3_debt_value = fields.Float()
    minimum_negotiation_payment = fields.Float()
    reference_minimum_installment = fields.Float()
    capital_sum = fields.Float()
    current_interest_sum = fields.Float()
    overdue_interest_sum = fields.Float()
    insurance_sum = fields.Float()
    other_charges_sum = fields.Float()
    minimum_payment = fields.Float()
    restrictive_list_codes = fields.Int()
    legal_process_stage = fields.Str()
    recovery_agent_code = fields.Str()
    certified_income = fields.Float()
    number_of_overdue_products = fields.Int()
