from marshmallow import Schema, fields


class ClientSchema(Schema):
    tipo_id = fields.Int(required=True)
    identificacion = fields.Int(required=True)
    nombre = fields.Str(required=True)
    telefono = fields.Str()
    correo = fields.Str()
    macroportafolio = fields.Str()
    probabilidad_pago = fields.Float()
    segmento_cliente = fields.Str()
    tipo_cliente = fields.Str()
    acciones_sobre_cliente = fields.Str()
    dias_mora = fields.Int()
    saldo_capital = fields.Float()
    rango_ingresos = fields.Str()
    tendencia_ingresos = fields.Str()
    endeudamiento_sector = fields.Float()
    suma_cuotas_sector = fields.Float()
    suma_cuotas_banco = fields.Float()
    nombre_entidad_1_deuda = fields.Str()
    valor_entidad_1_deuda = fields.Float()
    nombre_entidad_2_deuda = fields.Str()
    valor_entidad_2_deuda = fields.Float()
    nombre_entidad_3_deuda = fields.Str()
    valor_entidad_3_deuda = fields.Float()
    abono_minimo_negociacion = fields.Float()
    cuota_minima_referencia = fields.Float()
    suma_capital = fields.Float()
    suma_intereses_corriente = fields.Float()
    suma_intereses_mora = fields.Float()
    suma_seguros = fields.Float()
    suma_otros_cargos = fields.Float()
    pago_minimo = fields.Float()
    codigos_listas_restrictivas = fields.Int()
    etapa_procesos_juridicos = fields.Str()
    cod_recuperador = fields.Str()
    ingreso_certificado = fields.Float()
    numero_productos_mora = fields.Int()
