from marshmallow import Schema, fields


class ProductDataSchema(Schema):
    type_id = fields.Int(required=True)
    identification = fields.Int(required=True)
    cut_off_date = fields.Date(required=True)
    product_id = fields.Str(required=True)
    product_family = fields.Str()
    disbursement = fields.Float()
    term = fields.Int()
    interest_rate = fields.Float()
    installment = fields.Float()
    in_arrears = fields.Bool()
    days_in_arrears = fields.Int()
    capital = fields.Float()
    current_interest = fields.Float()
    arrears_interest = fields.Float()
    insurance = fields.Float()
    other_charges = fields.Float()
    accumulated_payments = fields.Float()
    total_balance = fields.Float()
    minimum_payment = fields.Float()
    promissory_note = fields.Bool()
    payment_date = fields.Date()
    preapproval_code = fields.Str()
    company = fields.Int()
    circular_026 = fields.Str()
    product_in_dollars = fields.Bool()


## schema in spanish ##
# class EsquemaDatosProducto(Schema):
#     tipo_id = fields.Int(required=True)
#     identificacion = fields.Int(required=True)
#     fecha_corte = fields.Date(required=True)
#     id_producto = fields.Str(required=True)
#     familia_producto = fields.Str()
#     desembolso = fields.Float()
#     plazo = fields.Int()
#     tasa_interes = fields.Float()
#     cuota = fields.Float()
#     en_mora = fields.Bool()
#     dias_en_mora = fields.Int()
#     capital = fields.Float()
#     interes_corriente = fields.Float()
#     interes_en_mora = fields.Float()
#     seguro = fields.Float()
#     otros_cargos = fields.Float()
#     pagos_acumulados = fields.Float()
#     saldo_total = fields.Float()
#     pago_minimo = fields.Float()
#     pagaré = fields.Bool()
#     fecha_pago = fields.Date()
#     codigo_preaprobacion = fields.Str()
#     compania = fields.Int()
#     circular_026 = fields.Str()
#     producto_en_dolares = fields.Bool()
