name: Deploy production
on:
  push:
    branches: [ production ]
    
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    name: Deploy production
    uses: davivienda-colombia/davi-coe-reusable-pipeline/.github/workflows/deploy_python_lambda.yml@main
    with:
      path-environments-variables: "pipeline/production-task-definition-virginia.json"
      environment: production

    secrets:
        DAVI_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DAVI_READER_GITHUB_ACCESS_TOKEN }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_ROLE_DEPLOY_BACKEND: ${{ secrets.AWS_ROLE_DEPLOY_BACKEND }}
